 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/meetings_apps", type: :request do
  
  # MeetingsApp. As you add validations to MeetingsApp, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MeetingsApp.create! valid_attributes
      get meetings_apps_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      meetings_app = MeetingsApp.create! valid_attributes
      get meetings_app_url(meetings_app)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_meetings_app_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      meetings_app = MeetingsApp.create! valid_attributes
      get edit_meetings_app_url(meetings_app)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MeetingsApp" do
        expect {
          post meetings_apps_url, params: { meetings_app: valid_attributes }
        }.to change(MeetingsApp, :count).by(1)
      end

      it "redirects to the created meetings_app" do
        post meetings_apps_url, params: { meetings_app: valid_attributes }
        expect(response).to redirect_to(meetings_app_url(MeetingsApp.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MeetingsApp" do
        expect {
          post meetings_apps_url, params: { meetings_app: invalid_attributes }
        }.to change(MeetingsApp, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post meetings_apps_url, params: { meetings_app: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested meetings_app" do
        meetings_app = MeetingsApp.create! valid_attributes
        patch meetings_app_url(meetings_app), params: { meetings_app: new_attributes }
        meetings_app.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the meetings_app" do
        meetings_app = MeetingsApp.create! valid_attributes
        patch meetings_app_url(meetings_app), params: { meetings_app: new_attributes }
        meetings_app.reload
        expect(response).to redirect_to(meetings_app_url(meetings_app))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        meetings_app = MeetingsApp.create! valid_attributes
        patch meetings_app_url(meetings_app), params: { meetings_app: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested meetings_app" do
      meetings_app = MeetingsApp.create! valid_attributes
      expect {
        delete meetings_app_url(meetings_app)
      }.to change(MeetingsApp, :count).by(-1)
    end

    it "redirects to the meetings_apps list" do
      meetings_app = MeetingsApp.create! valid_attributes
      delete meetings_app_url(meetings_app)
      expect(response).to redirect_to(meetings_apps_url)
    end
  end
end
